### ISSUE TITLE
Adventure > Rhom > "Soul Link" ring not appearing / not included in analysis

### ISSUE THREAD

**Issue by GregariousJB** [Razzmatazzz/RemnantSaveManager#20]
I'm reasonably sure this is a bug after about two dozen Adventure rerolls with Rhom. Either that or I have horrible luck. 

https://remnantfromtheashes.wiki.fextralife.com/Soul+Link

Apparently the Soul Link ring is supposed to appear in a cave beside a Cryptolith (or perhaps the area is called "Cryptolith"?), shown in this video: https://www.youtube.com/watch?v=bM0032AatdU

Unrelated: This program is fucking amazing. Thank you for making it and keeping it up to date!

**Comment by Razzmatazzz** [comment]
Yes, the Soul Link should spawn with the Cryptolith on Rhom. There isn't actually a separate event in the save file for it, so the analyzer [manually adds it when Cryptolith appears on Rhom](https://github.com/Razzmatazzz/RemnantSaveManager/blob/master/RemnantWorldEvent.cs#L189).

It's possible this behavior changed with this past week's patch. Have you seen the Cryptolith on Rhom in the analyzer without Soul Link also appearing? If so, has this been exclusively within the past few days (since the latest patch) or for a longer period of time?

**Comment by GregariousJB** [comment]
Admittedly I haven't been looking for "Cryptolith", only the red-text "Soul Link". I'll do a bunch more rerolls and see if the Cryptolith pops up.

**Comment by Razzmatazzz** [comment]
AFAIK, Soul Link doesn't appear separately from the Cryptolith. You need to get Cryptolith in order to get Soul Link.

**Comment by GregariousJB** [comment]
Done about 20 more Adventure rerolls and I haven't seen "Cryptolith" or "Soul Link" in any columns (checking all of them this time). I have seen "Monolith" but I think that's the floor puzzle thingy that gets you the Void Set.

If Cryptolith is an area, wouldn't Soul Link show up in red text since it's a missing item?

I'm not sure how your code works, but would it also need to be listed here under the Cryptolith events in order for it to show up? https://github.com/Razzmatazzz/RemnantSaveManager/blob/10ff549628d4148f13bb2c9f2e6bfbcbf1bfba22/Resources/GameInfo.xml#L142

**Comment by Razzmatazzz** [comment]
If you're not seeing Cryptolith, that's why you're not seeing Soul Link. As I already stated, Rhom does not roll an independent Soul Link event. Soul Link is essentially part of the Cryptolith spawn on Rhom. That's why I manually add the Soul Link event when Cryptolith appears on Rhom (the code I linked in my initial response). Once Soul Link is manually added, it will appear as a separate event right below Cryptolith. Because that manually-added Soul Link event [is included in the GameInfo.xml](https://github.com/Razzmatazzz/RemnantSaveManager/blob/10ff549628d4148f13bb2c9f2e6bfbcbf1bfba22/Resources/GameInfo.xml#L363), it will show as a missing item when you don't have it.

You're correct that Monolith is a different event.

I think one of two things is happening: (1) you're getting exceptionally bad luck and haven't rolled Cryptolith on Rhom; or (2) they changed something about Cryptolith and it either doesn't spawn on Rhom anymore or the event name was modified so the analyzer doesn't detect it properly and doesn't know to add Soul Link.

**Comment by GregariousJB** [comment]
Ok, I think I figured it out - I'm probably an idiot.

I was looking up Summoner build rings and found the Soul Link on the wiki, but it doesn't mention needing the DLC at all. I just have the free base game from when the game was free a day or so ago. 

I just asked someone in Discord if they've been having similar issues with the Soul Link rolling in their game and this random dude helped me pick it up after he screenshotted it for me: 

![image](https://i.imgur.com/Fxd8njo.png)

So I join his game, grab the ring, and lo and behold:

![image2](https://i.imgur.com/6IjHizk.png)

...I can't use it. And I'm guessing I would've needed the DLC to roll it, which explains why it didn't show up in your program. Oops. Sorry about that.
