### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by oleedd** [Razzmatazzz/RemnantSaveManager#29]
Possible to display all maps with location (or bosses) names?

**Comment by Razzmatazzz** [comment]
Are you asking if it's possible to read the save file and then generate a visual map that shows the locations of all the items and events? If so, then no.

**Comment by oleedd** [comment]
It is about events, not all items. Why no? Saves should contain this. Is it encrypted?

**Comment by Razzmatazzz** [comment]
That information isn't present in any readily-accessible form within the save files, as far as I can tell. If you want to dig around in the save files and prove me wrong, more power to you.

**Comment by oleedd** [comment]
Do you mean that the map is generated (and saved) after the first appearing in that location?

**Comment by oleedd** [comment]
Do you mean that the map is generated (and saved) at the first appearance in that location?

**Comment by Razzmatazzz** [comment]
I have no idea if that's how it works. All I know is that, to my eye, the list of events is about as much of a "map" as you can pull from the save file. But feel free to take a look yourself and see if you can make more sense of it.

**Comment by oleedd** [comment]
The point of this is that main locations are big and the player speed is slow - it is long to check all dungeons.
Maybe you will find this possible one day. The main thing is to understand whether it is in saves in any look or it is generated after the first visit to each location. So you can try to find the map of the first location (after visiting), which should be in saves 100%, and see whether there are other maps or no.

**Comment by Razzmatazzz** [comment]
Perhaps I've been unclear, which is my fault. The save file does not contain map layout information in any readily-human-readable form. While some information about map layout is probably saved, I have no idea what that information is. It could simply be the "seed" that the game then uses to generate the map. If that's the case, without knowing all the game's program logic of how to build a map from a seed, even knowing the seed would be useless in generating a map. Or maybe more detailed map information is contained in the save file but it's encoded in such a way that a human can't directly decipher its meaning. The point is, and I want to be 100% clear about this, **the save files do not contain map layout information that I am able to use to generate a visual map**. It's fairly clear from your responses that you've spent zero time scrutinizing save files, so don't presume to know what I "can try" to do to investigate your pet theories. I'm not going to spend more of my time looking through save files trying to find information that I don't believe is there. That's why I've encouraged you to go ahead try to find that information. If this feature is so important to you, you are welcome to invest your own time an energy in figuring it out.

**Comment by oleedd** [comment]
Ok. I understood.
>that you've spent zero time scrutinizing save files

But I know nothing on this topic.

**Comment by Razzmatazzz** [comment]
That's basically my point. You know nothing about this topic, yet you come here and repeatedly ask me to try and do things I've repeatedly told you aren't possible.

**Comment by oleedd** [comment]
The thing is I thought that if you could read some data of saves, you are able to read all data. But you let to understand that it is not so. I thought that the data in saves is in the same format, which allows to read all.
