### ISSUE TITLE
SaveManager interacts with other programs(?)

### ISSUE THREAD

**Issue by DaveJK** [Razzmatazzz/RemnantSaveManager#4]
Lemme start off by saying great program! I am very grateful as a new player starting out because of the current Steam sale. Now on to the interesting stuff.

This isn't much of an issue but I found it weird so I thought I would let you know. Before using your save manager I was using a Batch file I wrote named 'Remnant Backup' that was copying save files to a folder named 'Remnant Backup'. I didn't think nothing of it but pointed the save manager to the 'Remnant Backup' folder and when I click 'Open backups folder' it launches the Batch file. 

https://gfycat.com/baggyfirsthanddavidstiger

**Comment by Razzmatazzz** [comment]
That's interesting; thanks for reporting!

I use a shorthand to open the backup folder by just starting a process using a text string pointing to the backup folder (e.g., "%LocalAppData%\Remnant\Saved\Backups"). Am I correct in guessing that you have a folder that contains both the "Remnant Backup.bat" file and "Remnant Backup" folder? I think what's happening is the system is getting the command to start a process for "[path to folder]\Remnant Backup" and is choosing to run the .bat file instead of open the folder. I think I can fix the problem by just adding a trailing backslash to the string.

In the meantime, can you verify that the folder opens as expected if you rename the batch file something else (e.g., "RemnantBackup.bat")? I want to be sure there isn't something else going on when the backup folder is changed by the user.

**Comment by DaveJK** [comment]
Yeah, I renamed the bat file to 'Old Remnant Backup' and the Save Manager now opens the backup folder 'Remnant Backup' instead of the bat file.

**Comment by Razzmatazzz** [comment]
Ok, latest release should fix the issue even if the folder and the batch file have the same name. Thanks for reporting!
