### ISSUE TITLE
Can't open program。

### ISSUE THREAD

**Issue by strike94** [Razzmatazzz/RemnantSaveManager#44]
my pc is win10,and .net Framework is 4.8,but I can't open the program. Is it only open by 4.7.2?

**Comment by Razzmatazzz** [comment]
You can have multiple versions of the .NET Framework installed at once. If you install 4.7.2 in addition to 4.8, it should work.

**Comment by Flandre5carlet** [comment]
Hey, I have this same issue. I can't install 4.7.2 because the installer tells me I already have a more recent version of .NET installed.

**Comment by Razzmatazzz** [comment]
If it says you've already got that version or later, then the app _should_ run.

**Comment by Flandre5carlet** [comment]
I figure as much. What happens when I try to start it is that the process starts for a second or so, then closes by itself. No window appears, no error, or anything. It just effectively doesn't open at all... It's very odd.

**Comment by Razzmatazzz** [comment]
Do the following folders exist on your PC?
%LocalAppData%\RemnantSaveManager\RemnantSaveManager.exe_Url_[random characters]\1.96.0.0
%LocalAppData%\Remnant\Saved

**Comment by Flandre5carlet** [comment]
I can confirm the former exists (and one for the previous version as well)
The latter does not. For what it's worth I'm getting the game through Windows Store as part of the Game Pass, and it is not installed on the default drive.

**Comment by Razzmatazzz** [comment]
Aha, that's the issue then. The program is assuming the default save path (at least for Steam/EGS) exists and is running into an error because it doesn't exist. I'm not sure where the Windows Store version saves game data. Just for a guess, do you see anything related to Remnant in your "%UserProfile%/Saved Games" folder?

**Comment by Flandre5carlet** [comment]
Okay this is gonna be a bit long because this whole Microsoft Store thing seems to make a bit of a mess, folders wise.

So for one, there's nothing relating to Remnant in %userprofile%\Saved Games.
I have checked My Documents\My Games as well but nothing there either.

I have found a folder Remnant\Saved, located in:
`E:\WpSystem\S-1-5-21-abunchofnumbers\AppData\Local\Packages\PerfectWorldEntertainment.RemnantFromtheAshes_jrajkyc4tsa6w\LocalCache\Local\Remnant\Saved `
(E being the drive I install games on) and contains three folders (Config, Logs, SaveGames), the latter two are empty however.

After looking up online where save games might be for Microsoft Store games, I've found `%LocalAppData%\Packages`.

Indeed in the following path:
`C:\Users\[USERNAME]\AppData\Local\Packages\PerfectWorldEntertainment.RemnantFromtheAshes_jrajkyc4tsa6w` there are a bunch of folders (or shortcuts to other folders, apparently? The logo is shortcut but the type says folder...)

![image](https://user-images.githubusercontent.com/12631741/118561039-bbcb2080-b76a-11eb-9975-5b9d54399f21.png)

Most of them seem empty, or contain folders that are also empty, except "SystemAppData" 

SystemAppData\Helium contains User.dat and UserClass.dat 

SystemAppData\wgs contains.. this, the date of which corresponds to when I last started the game (just earlier to check if I still had my save):
![image](https://user-images.githubusercontent.com/12631741/118561335-20867b00-b76b-11eb-8b7d-75c863611879.png)

"t" is empty, the other one then contains this:
![image](https://user-images.githubusercontent.com/12631741/118561382-2c723d00-b76b-11eb-9de0-ac0154e0691a.png)

and FINALLY, these extensionless files:
![image](https://user-images.githubusercontent.com/12631741/118561418-385dff00-b76b-11eb-8331-ef75da275b5b.png)

I wonder if these exxtensionless files are the saves, the one from yesterday at 18:27 is pretty much exactly when I stopped playing my character.

**Comment by Razzmatazzz** [comment]
Even if those are the save files, the fact that they have seemingly random file names and are located in a folder path containing random characters means it would be HUGE amount of work to try to sort out. Plus, the content of the files may be obfuscated in some way. If you post them here, I can at least tell if they look like save files or not.

**Comment by Flandre5carlet** [comment]
Here's the file with the date that corresponds to when I last played. I had to zip it because the file itself wasn't supported by GitHub. If this is what a Windows Store save file looks like, then maybe having an option to manually point to those folders, to alleviate for the seemingly random numbers and folder names? I have no clue how doable that would even be though.

[2C49697FF53A4BDDB2C0C9294C973DEB.zip](https://github.com/Razzmatazzz/RemnantSaveManager/files/6497174/2C49697FF53A4BDDB2C0C9294C973DEB.zip)

**Comment by Razzmatazzz** [comment]
That looks like a character's world save file. Unfortunately, it would take a MASSIVE rewrite to add support for this version. I'm not sure if that's something I can take on right now.

**Comment by Razzmatazzz** [comment]
Can you add all three of those files to a .zip and post them in issue #46 ?
